import { Html5 } from '@styled-icons/boxicons-logos/Html5';
import { Css3 } from '@styled-icons/boxicons-logos/Css3';
import { Javascript } from '@styled-icons/boxicons-logos/Javascript';
import { Sass } from '@styled-icons/boxicons-logos/Sass';
import { ReactLogo } from '@styled-icons/boxicons-logos/ReactLogo';
import { Styledcomponents } from '@styled-icons/simple-icons/Styledcomponents';
import { Firebase } from '@styled-icons/boxicons-logos/Firebase';
import { Git } from '@styled-icons/boxicons-logos/Git';
import { Nodejs } from '@styled-icons/boxicons-logos/Nodejs';
import { Webpack } from '@styled-icons/simple-icons/Webpack';
import { Npmjs } from '@styled-icons/remix-fill/Npmjs';
import styled from 'styled-components';
